### ISSUE TITLE
Update the consistency check 

### ISSUE THREAD

**Issue by gretelliz** [kytos-ng/mef_eline#188]
Update the consistency check according to blueprint https://github.com/kytos-ng/kytos/pull/278 for flow_stats stabilization v1. That is, consistency check will only run for EVCs that are enabled, inactive and haven't been updated within a time interval slightly greater than flow_manager.settings.CONSISTENCY_MIN_VERDICT_INTERVAL = 60 * 2, and haven't got flows removed recently.

**Comment by viniarck** [comment]
@gretelliz, regarding this part here from the blueprint, we left a part there to discuss:

> Evaluate if the new time interval will be set on `settings.DEPLOY_EVCS_INTERVAL` or a new one and impact on existing adaptations on the existing `WAIT_FOR_OLD_PATH`.

Since `mef_eline` will subscribe to `kytos/flow_manager.flow.removed` (that relies on `send_flow_rem`) to keep track of recent deleted flows and only run the consistency for EVCs that haven't had recent deleted flows (we'll need to defined what recent means for mef_eline, but probably one iteration), and considering that the new `PUT /traces` that you'll integrate on https://github.com/kytos-ng/mef_eline/issues/190 since will filter for `state=installed`, then **I think** we can keep the `settings.DEPLOY_EVCS_INTERVAL` and  `WAIT_FOR_OLD_PATH` as they are but I think we'll need to adapt the `self.execution_rounds` to be EVC-aware instead of global, otherwise we could have rare edge cases where a set of EVCs might still be converging (in an extreme very slow hypothetical case) but then it would try to redeploy again snowballing things unnecessarily. 

I'll advise to collect feedback from @italovalcy regarding general advice and/or potentially using `self.execution_rounds` EVC-aware instead of global, and maybe also have a way to reset the execution_rounds if they'll be EVC-aware.
