### ISSUE TITLE
Review exceptions handled when calling flask.request.get_json

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#243]
Hi,

We are doing exception handling for `ValueError` when calling `flask.request.get_json()` in https://github.com/kytos-ng/mef_eline/blob/master/main.py#L948-L951

However, the Flask lib only seems to raise BadRequest if the JSON parser code fails (internally, Flask.request utilizes the ValueError, but this is not sent to the caller). I believe it is safe to remove the ValueError validation

**Comment by viniarck** [comment]
This is no longer an issue since `flask` was replace with `starlette` and `kytos.core.rest_api` is providing helper functions that will raise `HTTPException` https://github.com/kytos-ng/kytos/blob/master/kytos/core/rest_api.py#L48-L63 and `mef_eline` is using them. I'll go ahead and close the issue.
