### ISSUE TITLE
Error changing the UNI via UI - None for not nullable for field primary_constraints/spf_max_path_cost

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#315]
If you create a circuit and want to just change the UNI_a/UNI_z via UI, Kytos gives you an error as showed below:

```
{
    "code": 400,
    "description": "The request body contains invalid API data. None for not nullable for field primary_constraints/spf_max_path_cost.",
    "name": "Bad Request"
}
```

Enabling dev mode on the browser shows the following payload being sent:

```
{"name":"EVC_Test_1","enable":true,"dynamic_backup_path":true,"sb_priority":null,"bandwidth":0,"queue_id":null,"service_level":0,"uni_a":{"interface_id":"00:00:00:00:00:00:00:01:11","tag":{"tag_type":1,"value":198}},"uni_z":{"interface_id":"00:00:00:00:00:00:00:02:4","tag":{"tag_type":1,"value":198}},"primary_constraints":{"desired_links":[],"undesired_links":[],"spf_attribute":"hop","spf_max_path_cost":null,"minimum_flexible_hits":null,"mandatory_metrics":{"ownership":""},"flexible_metrics":{"ownership":""}},"secondary_constraints":{"desired_links":[],"undesired_links":[],"spf_attribute":"hop","spf_max_path_cost":null,"minimum_flexible_hits":null,"mandatory_metrics":{"ownership":""},"flexible_metrics":{"ownership":""}}}
```

It looks like we need a way to only submit parameters that were changed or accept Null values on the spec.

**Comment by viniarck** [comment]
@italovalcy thanks for reporting this. 

This is a UI implementation bug. UI client should be following that the [PATCH /v2/evc/{circuit_id}](https://github.com/kytos-ng/mef_eline/blob/master/openapi.yml#L108) expects. 

There are many attr being set as `null` which are invalid, otherwise it'll return bad request as expected. Empty list values for `primary_path`, `backup_path`, `desired_links` and `undesired_links` indeed can have valid semantics, but only if the user actually meant that they want an empty list (for folks not familiar with this check out this for example https://github.com/kytos-ng/mef_eline/issues/230). The least surprising route is for the UI to only send what needs to be updated, even though it could also send attrs that haven't changed, but it would also lead to harder to debug down the line, so I wouldn't recommend going down that route.

@rmotitsuki can you add this one to your radar for `2023.1`?
