### ISSUE TITLE
`mef_eline` should allow to set on a default queue to be used when an EVC is created

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#350]
This is for introducing a default `QUEUE_ID` that should be used when an EVC is first created. It should be backwards compatible, so on settings.py the default value should be `QUEUE_ID = None`, but network operators might start to use a different value.

**Comment by Alopalao** [comment]
It is desired that `queue_id` value changes with the default value in `settings.py`. To do this there is some complications with the implementation.
1. `queue_id` is from `attributes_requiring_redeploy`. To have a changing value, it is necessary to redeploy the EVC with this default value. It could be done with `consistency_check` for EVCs but we need to know the previous value (compare change) and know that it should be default. It could be done with:
- Changing database format: Changing the `queue_id` value from `Optional[int]` to `dict` that would look like `{"value": 2, "default": False}`

**Comment by viniarck** [comment]
After thinking more about it, I think we shouldn't support dynamic `queue_id`, the `None` deletion semantics make it more difficult to deal with, except if it's going to be only for creation, and then during creation to use whichever default value it is at that time, and then explicitly sets that value. If any new value is needed, then network operators can update all EVCs accordingly. In the future, we could also provide a bulk update endpoint if ever needed, but let's say if you need to change all queue_ids to another value, iterating over EVCs isn't difficult for a caller to do either. Also, `queue_id` in practice likely won't keep changing frequently for generic use cases (please correct me if I'm wrong if that's not the case for AmLight), so I have an impression, that unlike `spf_attribute` the price to pay in terms of implementation for both back-end and front-end changes is a bit higher for very little convenience. 

Also, as it is, the API is explicitly consistent and easy to understand, including for future contributors or users. Aldo's option 2 would be more closely to how `spf_attribute` currently behaves, but then in the runtime it'll still need to use another auxiliary value or dict representation (even if in the data model it were to be not set), but it's not trivial to maintain compared with what we currently have, and having a new special value doesn't make it easy for callers either.

Would just supporting `queue_id` default for when EVC is first created be sufficient? Or should we not support this at all? Let me know what you guys think, if you have any other major reasons that should be taken into account.

**Comment by italovalcy** [comment]
In my opinion, the queue ID option for EVCs should work in the simplest possible way. By that I mean:

a) When creating a EVC, if the user provided the queue-ID, go with the value provided by user. If the user didn't provide the queue ID, get the default value from settings and apply that value. (here I believe the valid values should be [None, 0, 1, 2, 3, 4, 5, 6, 7])
b) When the network operator just change the settings to modify the default queue ID from None (default value) to 1, no change should be applied to deployed EVCs. New EVCs will follow the path described above (a)
c) If the user requests an EVC redeploy, or changed any attribute on the EVC which trigger a redeployment, or yet the EVC was redeployed due to link UP/Down event, then it is a another time to change the queue ID according to the settings
d) if the network operator changes the settings and modify the default queue ID from None to 1, the default value should not be stored on the EVC data model (MongoDB). Instead, the default queue ID configured via settings should stay only on settings
e) optionally, we can provide migration scripts to bulk update EVCs and change/remove/insert queue_id (still in doubt if this is really necessary)

**Comment by Alopalao** [comment]
Oh, I was thinking more on an active redeploying so not EVCs with default settings is left behind. I think having an extra integer value (-1 or 8) to represent default settings will be better in this case. This value will be set when if there is not value when creating an EVC. It will be shown in the UI and the response for API requests.
